# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/decimal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/decimal.proto',
  package='cqg',
  syntax='proto2',
  serialized_options=b'B\014DecimalProto',
  serialized_pb=b'\n\x14\x63ommon/decimal.proto\x12\x03\x63qg\"6\n\x07\x44\x65\x63imal\x12\x16\n\x0bsignificand\x18\x01 \x01(\x12:\x01\x30\x12\x13\n\x08\x65xponent\x18\x02 \x01(\x11:\x01\x30\x42\x0e\x42\x0c\x44\x65\x63imalProto'
)




_DECIMAL = _descriptor.Descriptor(
  name='Decimal',
  full_name='cqg.Decimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='significand', full_name='cqg.Decimal.significand', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exponent', full_name='cqg.Decimal.exponent', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Decimal'] = _DECIMAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DECIMAL,
  '__module__' : 'common.decimal_pb2'
  # @@protoc_insertion_point(class_scope:cqg.Decimal)
  })
_sym_db.RegisterMessage(Decimal)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
